### ISSUE TITLE
DoNotCompare doesn't hold if a comparer for that type is added.

### ISSUE THREAD

**Issue by DerekBriske** [ValeraT1982/ObjectsComparer#4]
If you have an object in which you want to utilize the stringIgnoreCase comparer, and any property you do not want to compare that is a string is now comparing.

Given the Example1Tests, if you update the set up comparer, and include a ingoreCaseStringsValueComparer, the .Id do not compare no longer sticks. the equal unit test fails. 

I would think that the donotcompare, should stick and take priority.

` public void SetUp()
        {
            _comparer = new Comparer<Message>(
                new ComparisonSettings
                {
                    //Null and empty error lists are equal
                    EmptyAndNullEnumerablesEqual = true
                });
            //Do not compare Dates 
            _comparer.AddComparerOverride<DateTime>(DoNotCompareValueComparer.Instance);
            _comparer.AddComparerOverride<string>(IgnoreCaseStringsValueComparer.Instance);

            //Do not compare Id
            _comparer.AddComparerOverride(() => new Message().Id, DoNotCompareValueComparer.Instance);
            //Do not compare Message Text
            _comparer.AddComparerOverride(() => new Error().Messgae, DoNotCompareValueComparer.Instance);
        }`

**Comment by ValeraT1982** [comment]
@DerekBriske in current implementation if you override comparer by type this comparer has highest priority. I don't exactly remember why I decided that it's a good idea. What you are saying make sense to me because overrides by member are more specific than overrides by type.
I committed a change to fix it and most likely this change will be in the next version. If you need it you can build package from the source code or wait for the next version.

Thanks a lot for your feedback. It helps to make this framework better.

**Comment by DerekBriske** [comment]
@ValeraT1982 that did the trick! I can't thank you enough! this is a great package. I'll pull the update down from nuget once its out there.

**Comment by bryans2k** [comment]
Would also be great if you could use NulableStringsValueComparer.Instance and IgnoreCaseStringsValueComparer.Instance together.

**Comment by ValeraT1982** [comment]
@bryans2k Good idea. I don't thin that it should be implemented as using comparers together, I'm thinking about adding a new one like NulableIgnoreCaseStringsValueComparer.

**Comment by ValeraT1982** [comment]
Fixed in 1.3
